const { User } = require('../dataBase');
const {
    autoGeneratedAdmin: {
        adminName,
        adminEmail,
        adminPassword,
        adminAddress,
        adminPhone,
        adminRole
    }
} = require('../config');

module.exports = async function checkIfDBEmpty() {
    try {
        const numberOfUsers = await User.count();

        if (numberOfUsers === 0) {
            const newUser = await User.create({
                name: adminName,
                email: adminEmail,
                password: adminPassword,
                address: adminAddress,
                phone: adminPhone,
                role: adminRole,
            });

            console.log('DataBase was empty, new record of administrator was created: ');
            console.log(newUser);
            console.log('Please, change password and renew data of administrator!');
        }
    } catch (error) {
        console.log(error);
    }
};
